"""
Alert model - Clinical alerts and notifications.

Tracks alerts generated by the system for patient deterioration or risk.
"""

from datetime import datetime
from sqlalchemy import Column, String, DateTime, ForeignKey, Text, Boolean, Integer
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
import uuid
import enum

from app.core.database import Base


class AlertSeverity(str, enum.Enum):
    """Alert severity levels"""
    LOW = "low"              # NEWS2 0-4, routine monitoring
    MEDIUM = "medium"        # NEWS2 5-6, increased monitoring
    HIGH = "high"            # NEWS2 7+, urgent clinical review
    CRITICAL = "critical"    # Immediate intervention required


class AlertType(str, enum.Enum):
    """Types of alerts"""
    NEWS2_HIGH = "news2_high"
    MEWS_HIGH = "mews_high"
    VITAL_THRESHOLD = "vital_threshold"
    SEPSIS_RISK = "sepsis_risk"
    SHOCK_RISK = "shock_risk"
    DETERIORATION = "deterioration"
    CUSTOM = "custom"


class AlertStatus(str, enum.Enum):
    """Alert status"""
    ACTIVE = "active"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"
    DISMISSED = "dismissed"


class Alert(Base):
    """
    Alert model - stores clinical alerts and notifications.
    
    Attributes:
        id: Unique alert ID
        patient_id: Reference to patient
        vitals_id: Reference to vitals observation that triggered alert
        alert_type: Type of alert
        severity: Alert severity level
        status: Current status of alert
        
        title: Short alert title
        message: Detailed alert message
        reason: Clinical reasoning for alert
        recommendations: Suggested actions (JSON array)
        
        triggered_at: When alert was triggered
        acknowledged_at: When alert was acknowledged by staff
        acknowledged_by: Staff member who acknowledged
        resolved_at: When alert was resolved
        resolved_by: Staff member who resolved
        
        news2_score: NEWS2 score at time of alert
        mews_score: MEWS score at time of alert
        
        requires_escalation: Whether alert requires escalation
        escalated_to: Who alert was escalated to
        escalated_at: When escalated
        
        metadata: Additional alert data
    """
    
    __tablename__ = "alerts"
    
    # Primary key and foreign keys
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("patients.id"), nullable=False, index=True)
    vitals_id = Column(UUID(as_uuid=True), ForeignKey("vitals_observations.id"), nullable=True)
    
    # Alert classification
    alert_type = Column(String(50), nullable=False, index=True)
    severity = Column(String(20), nullable=False, index=True)
    status = Column(String(20), default="active", nullable=False, index=True)
    
    # Alert content
    title = Column(String(200), nullable=False)
    message = Column(Text, nullable=False)
    reason = Column(Text, comment="Clinical reasoning for alert")
    recommendations = Column(JSONB, default=list, comment="Suggested clinical actions")
    
    # Timestamps and staff
    triggered_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    acknowledged_at = Column(DateTime)
    acknowledged_by = Column(UUID(as_uuid=True), comment="Staff ID")
    resolved_at = Column(DateTime)
    resolved_by = Column(UUID(as_uuid=True), comment="Staff ID")
    
    # Clinical scores at time of alert
    news2_score = Column(Integer, comment="NEWS2 score")
    mews_score = Column(Integer, comment="MEWS score")
    
    # Escalation
    requires_escalation = Column(Boolean, default=False)
    escalated_to = Column(UUID(as_uuid=True), comment="Senior clinician ID")
    escalated_at = Column(DateTime)
    
    # Metadata
    metadata = Column(JSONB, default=dict, comment="Additional alert data")
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    patient = relationship("Patient", back_populates="alerts")
    
    def __repr__(self):
        return f"<Alert(type={self.alert_type}, severity={self.severity}, status={self.status})>"
    
    @property
    def is_active(self) -> bool:
        """Check if alert is still active"""
        return self.status == "active"
    
    @property
    def response_time(self) -> float:
        """Calculate response time in minutes"""
        if self.acknowledged_at:
            delta = self.acknowledged_at - self.triggered_at
            return delta.total_seconds() / 60
        return None
